In [6]:
import numpy as np

input = np.array([
    [8.5, 9.5, 9.9, 9.0],   # toes
    [0.65, 0.8, 0.8, 0.9],  # wlrec
    [1.2, 1.3, 0.5, 1.0]    # nfans
])

input_hidden_weight = np.array([
    [0.1, 0.2, -0.1],
    [-0.1, 0.1, 0.9],
    [0.1, 0.4, 0.1]
])

hidden_to_output_weight = np.array([
    [0.3, 1.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
])

input_0 = np.array([input[0][0], input[1][0], input[2][0]])

hidden_result = input_0.dot(input_hidden_weight)
output = hidden_result.dot(hidden_to_output_weight)

print(f"Input[0]\n{input_0}\n")
print(f"Input to hidden weight\n{input_hidden_weight}\n")
print(f"Hidden result\n{hidden_result}\n")
print(f"Hidden to output weight\n{hidden_to_output_weight}\n")
print(f"Output\n{output}\n")

Input[0]
[8.5  0.65 1.2 ]

Input to hidden weight
[[ 0.1  0.2 -0.1]
 [-0.1  0.1  0.9]
 [ 0.1  0.4  0.1]]

Hidden result
[ 0.905  2.245 -0.145]

Hidden to output weight
[[ 0.3  1.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   1.3  0.1]]

Output
[ 0.496  1.256 -0.286]

