In [2]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
import numpy as np

#########################################################################
# NN function
#########################################################################
def do_learning(inputs, initial_weights, expected_values, alpha):

    print("########################################")
    print(f"- Input             : \n{inputs}\n")
    print(f"- initial_weights   : \n{initial_weights}\n")
    print(f"- expected_value    : \n{expected_values}\n")
    print(f"- alpha             : \n{alpha}\n")
    print("########################################")
    
    need_learning = True
    weights = initial_weights
    iteration = 1

    inputs_size = inputs.size
    expected_values_size = expected_values.size

    weights = weights.reshape(inputs_size, expected_values_size)
    expected_values = expected_values.reshape(1, expected_values_size)

    while need_learning:
        print(f"==================== Iteration {iteration}")
        print("----- Setup -----")
        print(f"- Input             : \n{inputs}\n")
        print(f"- expected_value    : \n{expected_values}\n")
        print(f"- alpha             : \n{alpha}\n")
        print()

        # 2. NN Prediction
        print("----- NN Prediction -----")
        print(f"- weight            : \n{weights}\n")

        predicted_values = inputs.dot(weights)
        
        print(f"- predicted_value   : \n{predicted_values}\n")
        print()

        # 3. Calculate Error
        deltas = predicted_values - expected_values
        errors = deltas ** 2
        print("----- Calculate Error -----")
        print(f"- delta             : \n{deltas}\n")
        print(f"- error             : \n{errors}\n")
        print()

        # 4. Weight Adjustment
        error_derivatives = 2 * inputs * deltas
        # error_derivatives = error_derivatives.reshape(inputs_size, expected_values_size)
        error_derivatives = error_derivatives.reshape(inputs_size, 1)
        weight_adjustments = alpha * error_derivatives
        new_weights = weights - weight_adjustments
        print("----- Weight Adjustment -----")
        print(f"- error_derivative  : \n{error_derivatives}\n")
        print(f"- weight_adjustment : \n{weight_adjustments}\n")
        print(f"- new_weight        : \n{new_weights}\n")
        print()

        # 5. Still need learning?
        total_error = round(np.sum(errors), 5)
        need_learning = (total_error != 0)
        print("----- Need Learning -----")
        print(f"- total_error     : \n{total_error}\n")
        print(f"- need_learning     : \n{need_learning}\n")
        print()

        # Print information    

        # Update weight for next iteration
        weights = new_weights

        # Circuit breaker (max 1000 iteration)
        iteration = iteration + 1
        if(iteration > 1000):
            break


#########################################################################
# Run
#########################################################################

# Case 1: SISO
# This case will do 11 iterations until has zero error
# inputs = np.array([0.2])
# initial_weights = np.array([10])
# expected_values = np.array([8])
# alpha = 18

# Case 2: MISO
# This case will do 23 iterations until has zero error
# inputs = np.array([0.2, 4, 0.1])
# initial_weights = np.array([0, 0, 0])
# expected_values = np.array([8])
# alpha = 0.01

# Case 3: SIMO
# This case will do 120 iterations until has zero error
# inputs = np.array([0.2])
# initial_weights = np.array([10, 20, 3])
# expected_values = np.array([8, 46, 0.1])
# alpha = 24

# Case 4: MIMO
# This case will do xx iterations until has zero error
inputs = np.array([0.2, 2.3, 1.2])
# initial_weights = np.array([[7.1, 5.7, 2.2], 
#            [1.1, 3.0, 9.1], 
#            [4.4, 9.1, 7.0]])
initial_weights = np.array([[7.1, 1.1, 4.4], 
           [5.7, 3.0, 9.1], 
           [2.2, 5.3, 7.0]])
expected_values = np.array([8, 46, 0.1])
alpha = 0.2

do_learning(inputs, initial_weights, expected_values, alpha)

########################################
- Input             : 
[0.2 2.3 1.2]

- initial_weights   : 
[[7.1 1.1 4.4]
 [5.7 3.  9.1]
 [2.2 5.3 7. ]]

- expected_value    : 
[ 8.  46.   0.1]

- alpha             : 
0.2

########################################
==================== Iteration 1
----- Setup -----
- Input             : 
[0.2 2.3 1.2]

- expected_value    : 
[[ 8.  46.   0.1]]

- alpha             : 
0.2


----- NN Prediction -----
- weight            : 
[[7.1 1.1 4.4]
 [5.7 3.  9.1]
 [2.2 5.3 7. ]]

- predicted_value   : 
[17.17 13.48 30.21]


----- Calculate Error -----
- delta             : 
[[  9.17 -32.52  30.11]]

- error             : 
[[  84.0889 1057.5504  906.6121]]


----- Weight Adjustment -----
- error_derivative  : 
[[   3.668]
 [-149.592]
 [  72.264]]

- weight_adjustment : 
[[  0.7336]
 [-29.9184]
 [ 14.4528]]

- new_weight        : 
[[  6.3664   0.3664   3.6664]
 [ 35.6184  32.9184  39.0184]
 [-12.2528  -9.1528  -7.4528]]


----- Need Learning -----
- total_e

C:\Users\anton\AppData\Local\Temp\ipykernel_4584\4120727665.py:63: RuntimeWarning: overflow encountered in multiply
  total_error = round(np.sum(errors), 5)
z:\10__Python\3.12.4\Lib\site-packages\numpy\_core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\anton\AppData\Local\Temp\ipykernel_4584\4120727665.py:44: RuntimeWarning: overflow encountered in square
  errors = deltas ** 2
